const SET_CHATS = 'CHATS::SET_CHATS';
const ADD_CHAT = 'CHATS::ADD_CHAT';
const DELETE_CHAT = 'CHATS::DELETE_CHAT';
const FETCH_ADD_CHAT = 'CHATS::FETCH_ADD_CHAT';
const FETCH_DELETE_CHAT = 'CHATS::FETCH_DELETE_CHAT';
const CHANGE_CURRENT_CHAT = 'CHATS::CHANGE_CURRENT_CHAT';

export {
  SET_CHATS,
  ADD_CHAT,
  DELETE_CHAT,
  FETCH_ADD_CHAT,
  FETCH_DELETE_CHAT,
  CHANGE_CURRENT_CHAT,
};
