const GET_GISTS = 'GISTS::GET_GISTS';
const GET_GISTS_REQUEST = 'GISTS::GET_GISTS_REQUEST';
const GET_GISTS_SUCCESS = 'GISTS::GET_GISTS_SUCCESS';
const GET_GISTS_FAILURE = 'GISTS::GET_GISTS_FAILURE';

export { GET_GISTS, GET_GISTS_REQUEST, GET_GISTS_SUCCESS, GET_GISTS_FAILURE };
