const SIGN_UP = 'AUTH::SIGN_UP';
const FETCH_SIGN_UP = 'AUTH::FETCH_SIGN_UP';
const SIGN_UP_FAILURE = 'AUTH::SIGN_UP_FAILURE';
const SIGN_IN = 'AUTH::SIGN_IN';
const FETCH_SIGN_IN = 'AUTH::FETCH_SIGN_IN';
const SIGN_IN_FAILURE = 'AUTH::SIGN_IN_FAILURE';
const LOGOUT = 'AUTH::LOGOUT';
const FETCH_LOGOUT = 'AUTH::FETCH_LOGOUT';

export {
  SIGN_IN,
  SIGN_IN_FAILURE,
  FETCH_SIGN_IN,
  SIGN_UP,
  SIGN_UP_FAILURE,
  FETCH_SIGN_UP,
  LOGOUT,
  FETCH_LOGOUT,
};
