const CHANGE_SHOW_USERNAME = 'PROFILE::CHANGE_SHOW_USERNAME';
const CHANGE_USERNAME = 'PROFILE::CHANGE_USERNAME';
const SET_USERNAME = 'PROFILE::SET_USERNAME';
const SET_SHOW_USERNAME = 'PROFILE::SET_SHOW_USERNAME';

export {
  CHANGE_USERNAME,
  CHANGE_SHOW_USERNAME,
  SET_USERNAME,
  SET_SHOW_USERNAME,
};
